# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12CJW5fXyelBDPHxi9hJpWma8tTZIq6_E
"""

!pip install streamlit

import streamlit as st
import pickle
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer


# Load the model and vectorizer
# Modify the loading logic to load both from their respective files
try:
    with open('naive_bayes_model.pkl', 'rb') as model_file:
        model = pickle.load(model_file)
    with open('vectorizer.pkl', 'rb') as vectorizer_file:
        vectorizer = pickle.load(vectorizer_file)

except FileNotFoundError:
    st.error("Error loading model or vectorizer. Make sure 'naive_bayes_model.pkl' and 'vectorizer.pkl' are in the correct directory.")
    st.stop() # Stop execution if files are not found


# Page title
st.title('📧 Email Spam Filter')

# User input
input_email = st.text_area('✉️ Enter the email content below:', height=200)

# Button to classify
if st.button('Check if Spam'):
    if input_email.strip() == '':
        st.warning("Please enter an email message.")
    else:
        # Transform input text
        input_vector = vectorizer.transform([input_email])

        # Predict
        prediction = model.predict(input_vector)[0]

        # Show result
        if prediction == 1:
            st.error("🚫 This email is classified as **Spam**.")
        else:
            st.success("✅ This email is classified as **Not Spam**.")

